// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkvA1Xj1T4w6EdjbR4a6iudUgxw598Im0',
    appId: '1:135962169739:web:25556ee626651953e8df8e',
    messagingSenderId: '135962169739',
    projectId: 'ncsc-db',
    authDomain: 'ncsc-db.firebaseapp.com',
    storageBucket: 'ncsc-db.firebasestorage.app',
    measurementId: 'G-DHNENHZQ2D',
    databaseURL: "https://ncsc-db-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3xGW3xuby51a8WultfQR6SlX6k8ufLzA',
    appId: '1:135962169739:android:a82c4ea363cebd55e8df8e',
    messagingSenderId: '135962169739',
    projectId: 'ncsc-db',
    storageBucket: 'ncsc-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJB5Nd7RRRMFitWcfU4VKD0mU70rrDIc',
    appId: '1:135962169739:ios:704f1ff2d85e4558e8df8e',
    messagingSenderId: '135962169739',
    projectId: 'ncsc-db',
    storageBucket: 'ncsc-db.firebasestorage.app',
    iosBundleId: 'com.usm.ncsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJB5Nd7RRRMFitWcfU4VKD0mU70rrDIc',
    appId: '1:135962169739:ios:704f1ff2d85e4558e8df8e',
    messagingSenderId: '135962169739',
    projectId: 'ncsc-db',
    storageBucket: 'ncsc-db.firebasestorage.app',
    iosBundleId: 'com.usm.ncsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkvA1Xj1T4w6EdjbR4a6iudUgxw598Im0',
    appId: '1:135962169739:web:c21f9bc04709c97ce8df8e',
    messagingSenderId: '135962169739',
    projectId: 'ncsc-db',
    authDomain: 'ncsc-db.firebaseapp.com',
    storageBucket: 'ncsc-db.firebasestorage.app',
    measurementId: 'G-VG89PT4W6P',
  );
}
